CREATE TABLE IF NOT EXISTS chamados_n2 (
    numero_chamado TEXT PRIMARY KEY,
    titulo TEXT,
    prioridade TEXT,
    tipo_chamado TEXT,
    tipo_localizacao TEXT,
    localizacao TEXT,
    abertura TIMESTAMPTZ,
    situacao TEXT,
    status_sla TEXT,
    equipe_responsavel TEXT,
    responsavel TEXT,
    categoria TEXT,
    produto TEXT,
    problema TEXT,
    encerramento TIMESTAMPTZ,
    descricao TEXT,
    solucao TEXT,
    codigo_solucao TEXT,
    nivelsla TEXT,
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cargas_chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo TEXT,
    quantidade_registros INTEGER,
    carregado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chamados_abertura ON chamados_n2 (abertura);
CREATE INDEX IF NOT EXISTS idx_chamados_localizacao ON chamados_n2 (localizacao);
CREATE INDEX IF NOT EXISTS idx_chamados_problema ON chamados_n2 (problema);
CREATE INDEX IF NOT EXISTS idx_chamados_situacao ON chamados_n2 (situacao);


ALTER TABLE chamados_n2
ADD COLUMN IF NOT EXISTS nivelsla TEXT;
